# Generated by Django 4.0.3 on 2022-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RE', 'Records'), ('CL', 'Clothing'), ('PO', 'Posters'), ('MI', 'Miscellaneous')], default='RE', max_length=5),
            preserve_default=False,
        ),
    ]
