# Generated by Django 4.0.3 on 2022-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_band_like_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidon',
            field=models.BooleanField(null=True),
        ),
    ]
