# Generated by Django 4.0.3 on 2022-03-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_bidon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bidon',
        ),
    ]
