# Generated by Django 4.0.3 on 2022-03-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_listing_bidon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='bibliography',
            new_name='biography',
        ),
    ]
